package main

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	// Set seed for random number generation
	rand.Seed(time.Now().UnixNano())

	// Generate a random repo name and description
	repoName := fmt.Sprintf("github-repo-%d", rand.Intn(100))
	repoDesc := "Generated by github-repo-name-generator"

	// Print the result in JSON format
	fmt.Printf(`{"repo_name": "%s", "repo_desc": "%s"}`, repoName, repoDesc)
}
